<?php

namespace ContainerZafQ288;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RKIo74VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RKIo74V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RKIo74V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'creation' => ['privates', '.errored..service_locator.RKIo74V.App\\Entity\\Creations', NULL, 'Cannot autowire service ".service_locator.RKIo74V": it needs an instance of "App\\Entity\\Creations" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'creation' => 'App\\Entity\\Creations',
            'entityManager' => '?',
        ]);
    }
}
