<?php

namespace ContainerZafQ288;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WpnatSMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WpnatSM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WpnatSM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'creation' => ['privates', '.errored..service_locator.WpnatSM.App\\Entity\\Creations', NULL, 'Cannot autowire service ".service_locator.WpnatSM": it needs an instance of "App\\Entity\\Creations" but this type has been excluded in "config/services.yaml".'],
        ], [
            'creation' => 'App\\Entity\\Creations',
        ]);
    }
}
