<?php

namespace ContainerTajiEhp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IQXiIbBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iQXiIbB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iQXiIbB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'creation' => ['privates', '.errored..service_locator.iQXiIbB.App\\Entity\\Creations', NULL, 'Cannot autowire service ".service_locator.iQXiIbB": it needs an instance of "App\\Entity\\Creations" but this type has been excluded in "config/services.yaml".'],
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'creation' => 'App\\Entity\\Creations',
            'csrfTokenManager' => '?',
            'entityManager' => '?',
        ]);
    }
}
