<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTajiEhp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTajiEhp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTajiEhp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTajiEhp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTajiEhp\App_KernelDevDebugContainer([
    'container.build_hash' => 'TajiEhp',
    'container.build_id' => '5193bcaf',
    'container.build_time' => 1749501421,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTajiEhp');
